### ISSUE TITLE
Requires Array.find polyfill

### ISSUE THREAD

**Issue by rowanhogan** [everydayhero/boiler-room-runner#24]
There is [no IE support](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/find?v=example#Browser_compatibility) for `Array.prototype.find()`, including 11. Edge is fine.

Problem is here: https://github.com/everydayhero/boiler-room-runner/blob/master/source/client/index.js#L103

**Comment by bradparker** [comment]
Fixed in https://github.com/everydayhero/boiler-room-runner/pull/25 :+1:
